### PR TITLE
convert to war file

### PR DESCRIPTION
**Pull request by kyliel**

### CODE REVIEW

**Comment by kyliel** [comment]
Modify the sample project gs-spring-boot to generate war file.

**Comment by kyliel** [comment]
Those changes are only for war-based-deployment branch. Master is still original one for Jar package.

**Comment by gavinfish** [comment]
Then you should create a branch on this repo and merge change into that one instead of merging into `spring-guides:master`.

**Comment by kyliel** [comment]
Sorry, my mistake. Close this pull request.

**Pull request closed without merging**
