### PR TITLE
Fixes #89 - Fixed assertThat line which was always returning true

### LINKED ISSUE #89: HelloControllerIT assertion is always returning true
The test assertion is written incorrectly and always returns true.  You can verify this by changing the expected string to a bad value.

`assertThat(response.getBody().equals("Greetings from Spring Boot!"));`
should be changed to
`assertThat(response.getBody()).isEqualTo("Greetings from Spring Boot!");`

### PR DESCRIPTION
**Pull request by ccaspanello**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ccaspanello Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot&pullRequestId=90)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-boot&pullRequestId=90) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by dsyer** [comment]
I don’t think it’s actually broken. I agree that using the assertion api is better style , so I don’t mind merging if you can sign the CLA.

**Comment by ccaspanello** [comment]
Check out
https://github.com/spring-guides/gs-spring-boot/issues/89
It is actually broken in the sense that the assertion is not actually happening.  If you change the original implementation to a bad string it will essentially read `assertThat(false)`.

I found this out by mistake because I renamed my path location and realized when I went to the URL it was giving me a bad request error . . . but my unit tests were still "passing"

Optionally you could change assertThat to assertTrue and the test would work as intended; though the assertion API would give you better error messages when/if it fails.

**Comment by pivotal-issuemaster** [comment]
@ccaspanello Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot&pullRequestId=90)!

**Pull request merged**
